//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWA_Software.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausnahmen
    {
        public int PK_AusnahmeID { get; set; }
        public Nullable<int> Schüler { get; set; }
        public bool Gymnasium { get; set; }
        public bool Französisch_Pflichtfach { get; set; }
        public bool Italienisch_Pflichtfach { get; set; }
        public bool Latein_Pflichtfach { get; set; }
        public bool BE_Pflichtfach { get; set; }
        public bool Religion_Pflichtfach { get; set; }
    
        public virtual Schüler Schüler1 { get; set; }
    }
}
