//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWA_Software.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schüler_Tabelle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schüler_Tabelle()
        {
            this.Ausnahmen_Tabelle = new HashSet<Ausnahmen_Tabelle>();
            this.Wahlpflichtfächer_Tabelle = new HashSet<Wahlpflichtfächer_Tabelle>();
        }
    
        public int Schüler_ID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Klasse { get; set; }
        public string Passwort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ausnahmen_Tabelle> Ausnahmen_Tabelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wahlpflichtfächer_Tabelle> Wahlpflichtfächer_Tabelle { get; set; }
    }
}
