//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWA_Software.Datenbank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VWA_DatenbankEntities : DbContext
    {
        public VWA_DatenbankEntities()
            : base("name=VWA_DatenbankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ausnahmen> Ausnahmen { get; set; }
        public virtual DbSet<Schüler> Schüler { get; set; }
        public virtual DbSet<Wahlpflichtfächer> Wahlpflichtfächer { get; set; }
    }
}
