//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWA_Software.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wahlpflichtfächer_Tabelle
    {
        public int Wahlpflichtfach_ID { get; set; }
        public Nullable<int> Schüler { get; set; }
        public string Wahlpflichtfach_1 { get; set; }
        public string Wahlpflichtfach_2 { get; set; }
        public string Wahlpflichtfach_3 { get; set; }
        public string Wahlpflichtfach_4 { get; set; }
        public string Wahlpflichtfach_5 { get; set; }
    
        public virtual Schüler_Tabelle Schüler_Tabelle { get; set; }
    }
}
